### ISSUE TITLE
 Contact Us

### ISSUE THREAD

**Issue by devbn3li** [dragonsbootcampllc/spotalent_landingPage#11]
### We're Here to Help

Have questions or need support? Reach out to our team.

**[Contact Us](#)**

![Contact Us Image](contact-us.png)

## Footer

- **[About Us](#)**
- **[Careers](#)**
- **[Privacy Policy](#)**
- **[Terms of Service](#)**

![Social Media Icons](social-media.png)

**Comment by Kholoudxs55kh** [comment]
i need to know smthgs:

- the data we would request

- design ? https://cdn.dribbble.com/users/498594/screenshots/2722038/attachments/551199/screen_shot_2016-05-18_at_11.40.56.png : https://cdn.dribbble.com/users/93108/screenshots/2652785/media/1d3d2fc991fcf955e016756e9b929f19.jpg?resize=800x600&vertical=center : https://cdn.dribbble.com/users/4381465/screenshots/10722380/media/e524990fad6dde15e3d426fdb48dba68.png?resize=1000x750&vertical=center
